configMap:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "roboshop-dev.csnm4k0ikyug.us-east-1.rds.amazonaws.com" # here everytimechange rds endpoint

deployment:
  replicas: "1"
  imageName: "kopparthiprasanna/shipping"
  imageVersion: "1.4.0"